import stats from './stats.json';
import { BOOK, authorsLine, SITE_ORIGIN } from './book';

/**
 * Single source of truth for the book's canonical "what is this" definition —
 * consumed by both the visible on-page block (`DefinitionBlock`) and the
 * FAQPage JSON-LD (`whatIsThisBookJsonLd`), so the crawlable text and the
 * schema-extractable text can never drift apart. Numbers come from
 * `stats.json` (regenerated by `build_stats.py`), never hand-typed.
 */

export const WHAT_IS_THIS_BOOK_QUESTION = `What is "${BOOK.title}"?`;

export const whatIsThisBookAnswer = (): string =>
  `"${BOOK.title}" is a source-anchored book on AI engineering: how AI systems move from ` +
  `assistants that suggest, to copilots that collaborate in real time, to delegates trusted ` +
  `with full, reviewable tasks. Every claim links to a timestamped moment in one of ` +
  `${stats.corpus.videos} AI Engineer conference talks — ${stats.claims.total} claims backed by ` +
  `${stats.anchors.total} source anchors — and every chapter is scored by a panel of three rival ` +
  `open models (the book's own measurement engine, book-mash). Written by ${authorsLine}, ` +
  `published as an evolving public experiment at ${SITE_ORIGIN.replace('https://', '')}.`;

export const HOW_IS_THIS_DIFFERENT_QUESTION =
  "What makes this book's method different from other AI commentary?";

export const howIsThisDifferentAnswer = (): string =>
  `Most AI commentary is assertion without provenance. This book's claims layer works the other ` +
  `way: every claim in the ledger carries a Source Anchor — a precise video id and timestamp ` +
  `pointing at the moment a practitioner said it — plus a support level (strong, moderate, or ` +
  `tentative) instead of a flat citation. The claims ledger, chapter drafts, and chapter-by-chapter ` +
  `judge scores are all public and machine-readable, so the method is reproducible, not just the ` +
  `manuscript it produced.`;

export type DefinitionEntry = { question: string; answer: string };

/** The two Q&A pairs surfaced both in the page body and in FAQPage JSON-LD. */
export const bookDefinitionEntries = (): DefinitionEntry[] => [
  { question: WHAT_IS_THIS_BOOK_QUESTION, answer: whatIsThisBookAnswer() },
  { question: HOW_IS_THIS_DIFFERENT_QUESTION, answer: howIsThisDifferentAnswer() },
];
